services:
    php:
        build:
            context: ./docker/php-7.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                WWWUSER: 1000
        ports:
            - '8080:8080'
        environment:
            WWWUSER: 1000
        volumes:
            - '.:/var/www/html'
