services:
    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                WWWUSER: 1000
        ports:
            - '80:80'
        environment:
            WWWUSER: 1000
        volumes:
            - '.:/var/www/html'
